### ISSUE TITLE
Unable to have multiple working extensions

### ISSUE THREAD

**Issue by jimtremblay** [mate-desktop/python-caja#22] opened 2015-10-22 02:17 UTC
I have a working extension (caja-thg.py) in ~/.local/share/caja-python/extensions and if I copy the example submenu.py and restart caja, TortoiseHg disappear from menu and I'm only seeing the Foo->Bar example. Same behaviour if I try with other extensions like open-terminal.py and submenu.py: only one extension work at time.

I'm on Linux Mint 17.2 with Caja 1.10.3-1 and python-caja 1.8.1-2

**Comment by flexiondotorg** [comment] 2015-10-22 06:36
Just ran into this myself last night.

**Comment by monsta** [comment] 2015-10-23 09:02
Also reported in Mint forums, http://forums.linuxmint.com/viewtopic.php?f=206&t=205005

**Comment by monsta** [comment] 2015-12-07 15:19
Looks like this is a limitation of current extensions loading mechanism in Caja...

[Here](https://github.com/mate-desktop/caja/blob/master/libcaja-private/caja-module.c#L162) either zero or one type exposed by extension is used to register an extension. Not sure why zero types is allowed, but anyway, ```python-caja``` itself has no types and is registered alright... Now when you add some python extensions, each one registers one type... but only one type is used for registering, so all other python extensions aren't registered.

@alexandervdm: notifying you as the author of the extensions management feature :smile:

**Comment by flexiondotorg** [comment] 2016-01-01 23:58
@alexandervdm Can you look into this for us please?

**Comment by alexandervdm** [comment] 2016-01-14 11:36
Happy to report that this problem already existed in GNOME 2.30 (I didn't break it yay). I aim to look into this problem sometime in the coming weeks. Mid-Feb at the latest.

**Comment by monsta** [comment] 2016-01-14 12:54
Are you sure? People didn't stumble upon it until 1.10... the original module loading mechanism seemed to work fine in this case...

**Comment by monsta** [comment] 2016-01-31 12:02
Another downstream report: https://bugs.launchpad.net/bugs/1521206

**Comment by alexandervdm** [comment] 2016-02-24 18:46
@monsta You are right - I didn't test correctly. 

Apologies for missing the deadline. I will take care of this issue the coming weekend.

**Comment by monsta** [comment] 2016-02-25 08:36
Yes, would be nice to fix this before 1.14 release (I think we'll release it in March, or maybe beginning of April).

**Comment by alexandervdm** [comment] 2016-02-29 13:23
Found the issue and it was definitely a regression from my management code. Apologies for the inconvenience. The PR [here](https://github.com/mate-desktop/caja/pull/519) fixes the immediate problem. I'll follow up with another commit to have Python extensions listed separately in the management interface sometime later this week.

**Comment by monsta** [comment] 2016-03-01 08:15
Fixed in https://github.com/mate-desktop/caja/commit/8a826a675862d56b6d01c8467282bde9171f8cf8.

**Closed by monsta** 2016-03-01 08:15 UTC
Labels: confirmed
